### ISSUE TITLE
No Displayport audio after wake from sleep

### ISSUE THREAD

**Issue by weblogix** [billzhong/dell-precision-3240-compact-hackintosh#5]
Have you had any issues with displayport audio not working, after waking up from sleep?  

I was thinking it may be related to VoodooHDA but i've had no success with AppleALC.

**Comment by billzhong** [comment]
My monitor doesn't have speaker. I am using USB audio now.

Have you try AppleALC recently? Not sure if they fixed the issue relate to W480 chipset.

**Comment by weblogix** [comment]
I've not tried USB audio, but Bluetooth audio doesn't experience the issue.

I haven't been able to see any reports of issues or bugs with W480 chipset, in the AppleALC github or anywhere else.  Do you have a link to track the issue?

**Comment by bournesup** [comment]
Since Big Sur 11.3 breaks VoodooHDA, I find a solution to make AppleALC work on my 3440. It is due to IRQ conflicts, try to load SSDT-HPET with ACPI patch,and choose aclid=67, it should work. 
I am still having issues with restart and sleep, any inputs?

**Comment by billzhong** [comment]
@bournesup I still don't have a chance to take a look 3440 because that machine is running an uninterruptible project at the moment. I am using 3240 daily. How about I send you my 3240 BIOS's screenshots? Both BIOS should be identical. I remember it was settings in the BIOS causes the problem, but I can't remember which one exactly. You should be able to compare and find out.

**Comment by bournesup** [comment]
@billzhong email sent.

**Comment by weblogix** [comment]
@bournesup thanks for your help! I was able to get AppleALC working.  Just curious, how did you find out that it was an IRC conflict?

~~I am able to see line-out and internal speaker, but HDMI is not an available source.  Any tips?  I thought to change some framebuffer settings, but nothing that i've tried works.  I've also tried multiple layout id's, and hdmi audio did not show up.~~

I was able to get hdmi audio working.  Check my [repo](https://github.com/weblogix/hackintosh-dell-precision-3240-compact-comet-lake-opencore) for the code.  I've never had problems with sleep/wake since starting in 0.6.4, you may want to try out my config, too.

Thanks!
